### PR TITLE
ui update

### PR DESCRIPTION
**Pull request by Shivam36998**
hi sujal, 
i have some necessary changes, fixed the navbar and tried to make the ui bit pretty by organinsing data in cards...

### CODE REVIEW

**Comment by Shivam36998** [comment]
@Sujal-2820 please check it out, let me know if any problem appears

**Comment by Sujal-2820** [comment]
Hey @Shivam36998, I would recommend you to pull the latest changes from main branch to your branch. So of the code portions that you have been working on has been changed recently!!

Just check if you can enhance any portion of the code further. (please do not change the carousel format of the image)

Also test your code changes by deploying your branch on GitHub pages and send me a link of the same so that I can take a look at them.

All the Best👍

**Comment by Sujal-2820** [comment]
Hey @Shivam36998 
Can you provide the link to GitHub pages deployed for your branch so that it would be easy for me to track the changes

**Comment by Shivam36998** [comment]
@Sujal-2820 thanks for the suggestions, i will prefer to do it again and make another pr by evening

**Comment by Shivam36998** [comment]
@Sujal-2820 i need some suggestions 
can i still change the size of images and videos (height and width)

**Pull request closed without merging**
