### PR TITLE
added responsiveness for college reviews iframes

### PR DESCRIPTION
**Pull request by a-arham-x**
In index.html, I have updated the code for college reviews youtube iframes and added media queries to make them responsive to different screen sizes.

### CODE REVIEW

**Comment by Sujal-2820** [comment]
hey @a-arham-x
Can you provide the link to GitHub pages deployed to your branch.
I would be able to check the changes in a better way.

**Comment by Sujal-2820** [comment]
hey @a-arham-x
Can you provide the link to GitHub pages deployed to your branch.
I would be able to check the changes in a better way.

**Comment by a-arham-x** [comment]
> hey @a-arham-x Can you provide the link to GitHub pages deployed to your branch. I would be able to check the changes in a better way.

Sure. Here is the link to the deployed pages. [https://a-arham-x.github.io/Hacktoberfest-Web/](url)

**Comment by Sujal-2820** [comment]
Hey @a-arham-x,
I guess your branch is not deployed correctly, 
It's showing 404 error.\

Consider deploying the branch again.
All the best

**Comment by a-arham-x** [comment]
> Hey @a-arham-x, I guess your branch is not deployed correctly, It's showing 404 error.\
> 
> Consider deploying the branch again. All the best

I am sorry, For some reason my page is not opening if I comment the link here and gives the 404 error. If you copy and open the url https://a-arham-x.github.io/Hacktoberfest-Web/ in another tab, then it works.

**Review by Sujal-2820 — APPROVED** [review]
Good Work 👍

**Pull request merged**
